### DISCUSSION TITLE
display backdrop when user focus input

### DISCUSSION THREAD

**Discussion by AlonsoK28** [digitalfortress-tech/typeahead-standalone#46] [Ideas]
display backdrop may improve user UX

this options is already available into jQuery Typeahead http://www.runningcoder.org/jquerytypeahead/documentation/

example 
```js
// Custom light blue backdrop
backdrop: {
    "opacity": 0.15,
    "filter": "alpha(opacity=15)",
    "background-color": "#eaf3ff"
}
```

with backdrop enabled
![image](https://user-images.githubusercontent.com/37458700/212792276-97d754bc-e32b-4747-9759-2e6d593f298a.png)

without backdrop
![image](https://user-images.githubusercontent.com/37458700/212792323-cf3acbd9-5205-4ee1-bc5d-c249f557b814.png)

**Comment by AlonsoK28** [comment]
This could be done using CSS styles like this

```css
.tt-list {
  border-color: #ccc !important;
  // dropdown shadow example https: //codepen.io/connexo/pen/gmWjNJ
  box-shadow: 0 5px 13px #999;
}
```

![image](https://user-images.githubusercontent.com/37458700/215948937-63d9caae-7551-4083-a716-ca836cb8f9bd.png)
