### ISSUE TITLE
mouse hover and keyboard select design conflict 

### ISSUE THREAD

**Issue by alanjacobmathew** [digitalfortress-tech/typeahead-standalone#31]
### What happened?

Working with your example. 

There are 2 selections highlighted on the frontend , one with the keyboard selection and other with mouse hover 

### Affected version

Latest

### Reproduction URL

https://codepen.io/niketpathak/pen/vYRKdNq

### How to reproduce?

* Type the letter 'b'
* hover mouse over blue
* now use down arrow key

### Browsers

Firefox

### Additional context

![image](https://i.imgur.com/51O2qoZ.png)

**Comment by niketpathak** [comment]
Hello, this is not a bug. This is by choice to reuse the styling. 

The default css on hover can be overridden or rewritten as per your choice. 
For example 
```css
.tt-suggestion:hover {
   background-color: yellow;
}

/* You can also override the tt-selected element to distinguish between the hovered and the selected suggestion 
Don't forget to use higher specificity to ensure the desired styles are applied correctly.
*/
```
